### ISSUE TITLE
How to detect click on actionBar left icon when using this widget?

### ISSUE THREAD

**Issue by dkrusenstrahle** [FokkeZB/nl.fokkezb.drawer#13]
Thanks for a great widget!

I am having problems changing the actionBar icon (left) and detecting a click on it when using your widget. How can I do it?

**Comment by DouglasHennrich** [comment]
Hi Fokke, I look your example and I can't get it done on Android when using DrawerLayout... My $.drawer.addEventListener( 'open', function(){
    alert( 'test' );
});
Don't trigger... 
Do you have any suggestion ? Thanks
