### ISSUE TITLE
add children drawer to parent drawer

### ISSUE THREAD

**Issue by snaimika** [FokkeZB/nl.fokkezb.drawer#39]
how to add another sliding drawer on click event of one of the element of parent drawer

**Comment by FokkeZB** [comment]
Please be bit (well, maybe a lot) more specific on what you want, code examples etc.

**Comment by snaimika** [comment]
I am not able to add a submenu to the drawer.
I have added the following widget appnavigatortable to the drawer:
widget.xml: <Alloy> <ScrollView id="imagetable" width="100%" top="80" touchEnabled="true" scrollable="true" disableBounce="true" layout="vertical"> View onClick="startHome"> <Label id ="homelabel" class="btnlabel" text="Home" color="white"/> <Button id="homebutton" class="button" icon="fa-home"></Button> <Widget id="fa" src="com.mattmcfarland.fontawesome"/> </View>
        &lt;View onClick=&quot;startAccount&quot;&gt;
            &lt;Label id=&quot;accountlabel&quot; class=&quot;btnlabel&quot; text=&quot;Account&quot; color=&quot;white&quot;/&gt;
            &lt;Button id=&quot;accountbutton&quot; class=&quot;button&quot; icon=&quot;fa-user&quot;&gt;&lt;/Button&gt;
            &lt;Widget id=&quot;fa&quot; src=&quot;com.mattmcfarland.fontawesome&quot;/&gt;
        &lt;/View&gt;

        &lt;View onClick=&quot;startFindBranch&quot;&gt;
            &lt;Label id=&quot;findbranchlabel&quot; class=&quot;btnlabel&quot; text=&quot;Find Branch&quot; color=&quot;white&quot;/&gt;
            &lt;Button id=&quot;findbranchbutton&quot; class=&quot;button&quot; icon=&quot;fa-map-marker&quot;&gt;&lt;/Button&gt;
            &lt;Widget id=&quot;fa&quot; src=&quot;com.mattmcfarland.fontawesome&quot;/&gt;
        &lt;/View&gt;
</ScrollView> </Alloy>
I want to open a sub view on clicking on home button on the drawer.
<Alloy> <Widget id="drawer" src="nl.fokkezb.drawer"> <NavigationWindow id="mainview" platform="ios" role="centerWindow" fullscreen='true'> <Window fullscreen="true"></Window> </NavigationWindow> <View id="mainview" platform="android" role="centerWindow" zIndex="1" fullscreen='true'></View> <Window id="leftwin" module="xp.ui" role="leftWindow" theme="Theme.NoActionBar"> <View id="weatherview" left="2" right="2" top="2" height="80"> <ImageView id="weatherimgview" height="30" width="30" top="35" left="16" backgroundColor="transparent"></ImageView> <Label id="weathertemplabel" top="36" left="48" right="2" textAlign="left"></Label> <Label id="weatherdatelabel" top="5" left="5" right="5" textAlign="center"></Label> <Label id="weathertimelabel" top="15" left="5" right="5" textAlign="center"></Label> <Label id="weatherlocationlabel" top="64" left="5" right="5" textAlign="center"></Label> </View> <Widget src="com.rexel.appnavigatortable"></Widget> </Window> </Widget> </Alloy>

**Comment by FokkeZB** [comment]
Could you format the code in a way that I can read it (see markdown format options) and include the controller code?
