### ISSUE TITLE
[ERROR] Couldn't find module: xp.ui

### ISSUE THREAD

**Issue by Agnostic** [FokkeZB/nl.fokkezb.drawer#41]
I got this when I want to compile:

```[ERROR] Couldn't find module: xp.ui for architecture: i386```

I was looking for that module but it seems like it does not exist anymore.

**Comment by FokkeZB** [comment]
Please read the Android section of the readme where it explains xp.ui

**Comment by Agnostic** [comment]
I was using this for iOS

**Comment by SudoPlz** [comment]
For others hitting this error, the solution (as explained in the readme) is this:

Make a directory called `lib` within the `app` folder. Create a file named `ui.xp.js` and paste this code in it:

	exports.createWindow = function(args) {
	    return Ti.UI[OS_IOS ? 'createWindow' : 'createView'](args);
	};

and the error will be gone.
