### ISSUE TITLE
Android - dk.napp.drawer crash on start.

### ISSUE THREAD

**Issue by botmaster** [FokkeZB/nl.fokkezb.drawer#45]
Hello,

I would like to use your widget on Android with NappDrawer (without DrawerLayout).
I set "drawerLayout"  to "false" in index.tss file.
The widget work well with SDK 3.5.1 but fail with SDK >= 4.0.0
The application crashes when the "$.drawer.open" method is called. No errors are displayed.
Maybe NappDrawer module is not compatible with SDK 4.0.0

Start application log:
`[INFO]  TiApplication: (main) [0,0] checkpoint, app created.
[INFO]  TiApplication: (main) [53,53] Titanium 4.0.0 (2015/05/18 15:42 9239ff9)
[INFO]  TiApplication: (main) [26,79] Titanium Javascript runtime: v8
[INFO]  TiRootActivity: (main) [0,0] checkpoint, on root activity create, savedInstanceState: null
[INFO]  TiApplication: (main) [1,1] Analytics have been disabled
[WARN]  V8Object: (KrollRuntimeThread) [85,86] Runtime disposed, cannot set property 'userAgent'
[INFO]  TiRootActivity: (main) [0,0] checkpoint, on root activity resume. activity = fr.tests.alloy.drawer.widget.TestAlloyDrawerWidgetActivity@1c8e8284
[INFO]  I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 01/14/15, ab0075f, Id3510ff6dc
[INFO]  OpenGLRenderer: Initialized EGL, version 1.4
[INFO]  MOD: dk.napp.drawer
[WARN]  TiVerify: (Timer-0) [5018,5018] Verifying module licenses...
[INFO]  TiVerify: (Timer-0) [687,5705] Succesfully verified module licenses
[INFO]  Process: Sending signal. PID: 24746 SIG: 9`

**Comment by mano-mykingdom** [comment]
What is the version of NappDrawer module you are using?  

**You should update to 1.5.RC which is only compatible with 4.0**

**Comment by botmaster** [comment]
Hello Manoj,
I updated to 1.5.RC and everything is ok! 
Thanks.
