### ISSUE TITLE
just right and centre window - Android

### ISSUE THREAD

**Issue by kinski76** [FokkeZB/nl.fokkezb.drawer#46]
Hi

First thank you very much for creating this...it's great.

I have one quick question. I am attempting to just have a centre and right window. So i removed the left window markup form your index.xml example.

This works fine on iOS but on android I get:

-------
[ERROR] :  TiApplication: (main) [101,101] Sending event: exception on thread: main msg:java.lang.NullPointerException; Titanium 3.5.1,2015/03/05 10:08,96875c9
[ERROR] :  TiApplication: java.lang.NullPointerException
[ERROR] :  TiApplication: 	at com.slidingmenu.lib.CustomViewBehind.getSecondaryBehindWidth(CustomViewBehind.java:80)
[ERROR] :  TiApplication: 	at com.slidingmenu.lib.CustomViewBehind.scrollBehindTo(CustomViewBehind.java:251)
[ERROR] :  TiApplication: 	at com.slidingmenu.lib.CustomViewAbove.scrollTo(CustomViewAbove.java:806)
[ERROR] :  TiApplication: 	at com.slidingmenu.lib.CustomViewAbove.onSizeChanged(CustomViewAbove.java:468)
[ERROR] :  TiApplication: 	at android.view.View.sizeChange(View.java:14932)
[ERROR] :  TiApplication: 	at android.view.View.setFrame(View.java:14905)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:14813)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
[ERROR] :  TiApplication: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:14817)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
[ERROR] :  TiApplication: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
[ERROR] :  TiApplication: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
[ERROR] :  TiApplication: 	at android.view.View.layout(View.java:14817)
[ERROR] :  TiApplication: 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1983)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1740)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
[ERROR] :  TiApplication: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
[ERROR] :  TiApplication: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
[ERROR] :  TiApplication: 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
[ERROR] :  TiApplication: 	at android.view.Choreographer.doFrame(Choreographer.java:544)
[ERROR] :  TiApplication: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
[ERROR] :  TiApplication: 	at android.os.Handler.handleCallback(Handler.java:733)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:136)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5001)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:515)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
[ERROR] :  TiApplication: 	at dalvik.system.NativeStart.main(Native Method)
-----------------

I thought I would ask her first as I'm using the wrapper and have not tested the app.drawer independently(it states u can use left or right with centre aswell as both).

I am using Ti .3.5.1 with appcelerator studio 4 (latest release)

I am also not using the other drawer module for android...just napp.drawer for both iOS and Android

Wondered if you had any ideas on how to resolve or if I'm doing something utterly wrong:/?

**Comment by FokkeZB** [comment]
This is a limitation of the module, not the widget. Create an issue at https://github.com/manumaticx/Ti.DrawerLayout to request support center+right window only.
