### ISSUE TITLE
ActionBar click not work?

### ISSUE THREAD

**Issue by PietroGranati** [FokkeZB/nl.fokkezb.drawer#48]
I've just trasferred my app to appcelerator studio with sdk 4 and nappdrawer 1.5
The swipe to open works, but the click on the arrow doesn't.

Console tell me that actionBar is null?

**Comment by FokkeZB** [comment]
I'm 99% sure that's a module issue. Please report it at @viezel:
https://github.com/viezel/NappDrawer
