### ISSUE TITLE
FOr android 1.1.5 is not working 

### ISSUE THREAD

**Issue by harsukhbir** [FokkeZB/nl.fokkezb.drawer#50]

**Comment by adamkearsley** [comment]
You might want to add a description, error log, code example etc...?

**Comment by harsukhbir** [comment]
Well The things is 1.1.5 is not installed in my project its working only for IOS

**Comment by harsukhbir** [comment]
I am using gittio  and able to install only 1.1.4 not 1.1.5

**Comment by adamkearsley** [comment]
I think you are confused.

Firstly... this is not the NappDrawer module page, this is the FokkeZB page for the drawer widget.

The NappDrawer is only on V 1.1.4 (LATEST).
There is no 1.1.5 -- https://github.com/viezel/NappDrawer/releases

I have V 1.1.4 installed in my app (iOS and Android) and its working fine for both.

Maybe provide us with some example code?

**Comment by harsukhbir** [comment]
Yes I am bit confused due o work load. Now I have 1.1.4 installed in my project using your widget and I having following issues.

[ERROR] :  TiExceptionHandler: (main) [143,143] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,143] - In ti:/module.js:280,9
[ERROR] :  TiExceptionHandler: (main) [0,143] - Message: Uncaught Error: Requested module not found: xp.ui
[ERROR] :  TiExceptionHandler: (main) [0,143] - Source: 		throw new Error("Requested module not found: " + request);
[ERROR] :  V8Exception: Exception occurred at ti:/module.js:280: Uncaught Error: Requested module not found: xp.ui

**Comment by adamkearsley** [comment]
So you are missing the xp.ui library file.

You need a folder within `app` called `lib`.
Inside this folder you need a file called `xp.ui.js`.

It needs to contain:

`exports.createWindow = function(args) {
    return Ti.UI[OS_IOS ? 'createWindow' : 'createView'](args);
};`

**Comment by harsukhbir** [comment]
Thanks for your instant help. Now I am facing following issue.

[ERROR] :  TiExceptionHandler: (main) [199,199] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,199] - In ti:/module.js:280,9
[ERROR] :  TiExceptionHandler: (main) [1,200] - Message: Uncaught Error: Requested module not found: com.tripvi.drawerlayout
[ERROR] :  TiExceptionHandler: (main) [0,200] - Source: 		throw new Error("Requested module not found: " + request);
[ERROR] :  V8Exception: Exception occurred at ti:/module.js:280: Uncaught Error: Requested module not found: com.tripvi.drawerlayout

**Comment by adamkearsley** [comment]
In your index.tss you have specified
`drawerLayout: true`
This means you want to use a different drawer module called `drawerLayout`.
set it to false and it will use the nappDrawer module as default.

**Comment by harsukhbir** [comment]
Thanks for your help and its working fine for me now. One more question if you have the solution for that. Can We use click on the homeIcon to open the left window I mean the toggle button for open and close the left bar.

**Comment by FokkeZB** [comment]
@adamkearsley thanks for helping @harsukhbir 

@harsukhbir I don't get that last question.

**Comment by adamkearsley** [comment]
I think he wants to be able to use the hardware MENU button on an Android device to open and close the menu.
This would be cool and this module has a toggle command to open and close the menu...
But Appcelerator doesn't have an event listener for the menu button.

You can have a custom menu appear and these buttons have event listeners, but what you want isn't yet possible.
Maybe submit a request to Appcelerator for this?

**Comment by FokkeZB** [comment]
You could play with `Ti.Android.Activity.onPrepareOptionsMenu`. That callback should be called when the user presses the menu button.

**Comment by harsukhbir** [comment]
Hi,

Thanks for your kind help!

I am asking to implement the app icon click for open and close. For example Facebook.

**Comment by FokkeZB** [comment]
@harsukhbir that should work out of the box:
https://github.com/FokkeZB/nl.fokkezb.drawer/blob/master/nl.fokkezb.drawer/controllers/widget.js#L111

If it's not then you found a bug.

**Comment by harsukhbir** [comment]
I tested again Its not working .

**Comment by FokkeZB** [comment]
What versions of the Titanium SDK and DrawerLayout module are you using?

**Comment by harsukhbir** [comment]
I am using all latest. 
Lolipop
Titanium SDK 3.5.1
drawer module 1.1.4

**Comment by FokkeZB** [comment]
Well, that's not latest. This is:

Titanium SDK 4.0.0.GA
Napp Drawer Android 1.1.5
Napp Drawer iOS 1.2.1
DrawerLayout 1.3.3
Drawer widget 1.1.0 (or master)

And are we talking about iOS or Android? Since you don't mention drawerLayout?

**Comment by harsukhbir** [comment]
I am using this for Android and one more thing i need to ask. Can I change multi view like a tab group under the same actionbar.  Eg: I want to change view inside the centreWindow. what would i need to do. Kindly share if you have any sample application.

Thanks!

**Comment by FokkeZB** [comment]
Let's tackel one thing per issue shall we?

You are using it for Andorid, but with `drawerLayout` enabled or with using the NappDrawer module?

**Comment by harsukhbir** [comment]
Sure!

I have already set drawerLayout = false

**Comment by FokkeZB** [comment]
OK, then have a look at the [NappDrawer example](https://github.com/viezel/NappDrawer/blob/master/android/example/app.js#L219-L241) to see how you enable the use of the actionbar home-icon to close it. Please note that this might not work differently when you use Ti 4.0.0 with Material theme.

Closing this as it is not a widget issue.

**Comment by adamkearsley** [comment]
@harsukhbir you can use events to trigger drawer actions.
I wrote a few different global events for the drawer so i can use it on any page.

`Ti.App.addEventListener('toggleMenu', function(){
	$.drawer.toggleLeftWindow();
});`

Then use
`Ti.App.fireEventListener('toggleMenu');`
From anywhere in the app, regardless of where $.drawer was defined to toggle the left window.

You can use this method anywhere and on anything :)

**Comment by bacetach** [comment]
hi, 
I have this Error:
TiExceptionHandler: (main) [939,939] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,939] - In ti:/module.js:280,9
[ERROR] :  TiExceptionHandler: (main) [0,939] - Message: Uncaught Error: Requested module not found: xp.ui
[ERROR] :  TiExceptionHandler: (main) [0,939] - Source: 		throw new Error("Requested module not found: " + request);
[ERROR] :  V8Exception: Exception occurred at ti:/module.js:280: Uncaught Error: Requested module not found: xp.ui

I add the xp.ui library file. But the error still.

**Comment by FokkeZB** [comment]
See https://github.com/FokkeZB/nl.fokkezb.drawer#views-instead-of-windows

**Comment by bacetach** [comment]
Thank you.
I need to open the rightWindow (android) with a button, but I don't find the code to add the eventListner click:
![img_1up](https://cloud.githubusercontent.com/assets/14014764/9561812/48f450cc-4e4d-11e5-8529-fb56a4ad11e3.png)

**Comment by FokkeZB** [comment]
@bacetach here's how to add event listeners:
http://docs.appcelerator.com/platform/latest/#!/guide/Alloy_XML_Markup-section-35621528_AlloyXMLMarkup-BindingEvents
