### ISSUE TITLE
There's a way to use NavigationWindow from xp.ui ?

### ISSUE THREAD

**Issue by DouglasHennrich** [FokkeZB/nl.fokkezb.drawer#51]
I'm trying to use NavigationWindow from your xp.ui but on android side I'm getting this error when I open the app:

```
Cannot call method 'replace' of undefined
```

Here's my code for test:

```javascript
<Alloy>
    <Widget id="drawer" src="nl.fokkezb.drawer">

        <Window module="xp.ui" role="leftWindow" id="leftView">
            <Label>Test</Label>
        </Window>

        <NavigationWindow module="xp.ui" role="centerWindow" id="nav">
            <Window id="win">
                  <Label>Test</Label>
            </Window>
        </NavigationWindow>

    </Widget>

</Alloy>
```

Thanks

**Comment by FokkeZB** [comment]
You can't use the {{xp.ui}} version of {{NavigationWindow}} in the drawer widget, that's also why I don't have that in the example in the README. It only works when it's the top level element because it doesn't return a proxy but a plain JS object.

**Comment by DouglasHennrich** [comment]
That's sad =(

But thank you Fokke

**Comment by adamkearsley** [comment]
You can't have a NavigationWindow on Android...
You could use something like this...
```
<Alloy>
    <Widget id="drawer" src="nl.fokkezb.drawer">

        <Window module="xp.ui" role="leftWindow" id="leftView">
            <Label>Test</Label>
        </Window>

        <NavigationWindow platform="ios" role="centerWindow" id="nav">
            <Window id="win">
                  <Label>Test</Label>
            </Window>
        </NavigationWindow>
        <Window platform="android" module="xp.ui" role="centerWindow" id="nav">
                  <Label>Test</Label>
        </Window>

    </Widget>

</Alloy>
```

This would give Android a window and iOS a navigationWindow.

**Comment by FokkeZB** [comment]
@adamkearsley Indeed, and you could even use `<Require>` to re-use the same controller for the actual contents of that iOS Navigation Window and Android View.

**Comment by SudoPlz** [comment]
Thats really sad.. We could be using `open` and `close` in Android like we do in iOS if this worked.

I was searching all over the internet trying to find such a solution...

**Comment by FokkeZB** [comment]
See my answer to #59.
