### ISSUE TITLE
How can I expose the window on Android?

### ISSUE THREAD

**Issue by DouglasHennrich** [FokkeZB/nl.fokkezb.drawer#52]
Hi sir, there's a way to expose the window that the widget create on android side to add the drawer ?

I want to add listener on "open" event of that window but I want to do this on index.js file, not on widget.js file when the window is created.

There's a way to expose that window without attach it to Alloy.Globals ?

Thanks

**Comment by adamkearsley** [comment]
I cheat and use an event...
Ti.App.addEventListener

index.js
```
function openWindow(win, position)
{
	Ti.API.warn('open '+win);
	Ti.App.Properties.setString('curWin', win);
	
	var mywin = Alloy.createController(win).getView();
	$.drawer.openDrawerGestureMode = 'OPEN_MODE_ALL';
	switch(position) {
		case 'left': $.drawer.setLeftWindow(mywin); break;
		case 'center': $.drawer.setCenterWindow(mywin); break;
		case 'right': $.drawer.setRightWindow(mywin); break;
	}
}
Ti.App.addEventListener('openWindow', function(e){
	openWindow(e.win, e.position);
});
```

You can now use the fireEvent function anywhere in the app.
the win 'home' refers to home.js.
```
Ti.App.fireEvent('openWindow',{win:'home', position:'center'});
```

This works for both platforms.
I have events for toggle and bounceLeftWindow too...

Hope it helps!

**Comment by mano-mykingdom** [comment]
No need for adding any additional events.

If you are using `com.tripvi.drawerlayout` module, then simply follow this

```
var window = $.widgetId.getView();
```

Use this if `dk.napp.drawer`

```
$.widgetId.getView().addEventListener('open', function (e) {
var window =  this;
});
```

**Comment by DouglasHennrich** [comment]
hummm Thanks for your replies guys!

I will try your suggestion Mano, Thanks!
