### ISSUE TITLE
Is it possible to add 'opening' and 'closing' events

### ISSUE THREAD

**Issue by mawarnes** [FokkeZB/nl.fokkezb.drawer#56]
how difficult would it be to add opening and closing events that fire at the start of an open and a close? I've looked through the code but can't see an obvious place to start, any ideas?

**Comment by FokkeZB** [comment]
Both modules have events you can listen to:

- https://github.com/viezel/NappDrawer/tree/master/ios#events
- https://github.com/manumaticx/Ti.DrawerLayout/blob/master/documentation/index.md#events

You can add listeners via the `$.myWidgetInstance.instance` property.
