### ISSUE TITLE
Trying to fake nav not sure where i am going wrong

### ISSUE THREAD

**Issue by sobytes** [FokkeZB/nl.fokkezb.drawer#58]
Hi All,

Trying to fake the nav with the drawer menu with my own buttons using another widget everything opens fine but then it seems to lock and the app become unresponsive and i cant close anything here is my setup.

index.xml
~~~
<Alloy>
	<Widget id="drawer" src="nl.fokkezb.drawer">
		<Window module="xp.ui" role="leftWindow">
			<Label>I am left</Label>
		</Window>
		<Window navBarHidden="true">
			<Label id="leftNav" text="left" move="Left" onClick="toggle" left="0dp" />
			<Label id="rigthNav" text="right" move="Right" onClick="toggle" right="0dp"/>
		</NavigationWindow>
		<View platform="android" role="centerWindow">
		</View>
		<Window module="xp.ui" role="rightWindow">
			<Label>I am right</Label>
		</Window>
	</Widget>
</Alloy>
~~~

index.js
~~~
$.drawer.open();

function toggle(e) {
    var fn = 'toggle' + e.source.move + 'Window';
    $.drawer[fn]();
}

function windowSwipe(_event){
	console.log(_event);
} 
~~~

index.tss
~~~
"Window": {
    backgroundColor: "white"
}

"#drawer": {
    openDrawerGestureMode: "OPEN_MODE_ALL",
    closeDrawerGestureMode: "CLOSE_MODE_MARGIN",
    leftDrawerWidth: 300,
    rightDrawerWidth: 300,
    // use DrawerLayout for Android
    drawerLayout: false
}
~~~

Any suggestions am i missing a setting?

**Comment by FokkeZB** [comment]
@sobytes I'm sorry but I have to close this one. On first sight there's nothing strange I see, but I don't have time atm to dive into other people's code, in particular when other 3rd party modules and widgets are involved. Maybe open a topic on the Q&A?

**Comment by sobytes** [comment]
Hi @FokkeZB its nothing to do with the other module it still does it with the other module completely removed.

**Comment by FokkeZB** [comment]
Could you then at least try to get me a minimal reproducing test case so that we can for sure rule that out and make it easier to debug?

**Comment by sobytes** [comment]
@FokkeZB I've updated the issue

**Comment by FokkeZB** [comment]
Corrected your sample and could reproduce it on various Titanium SDKs and iOS Simiulators, also after simplifying it even a bit more.

Then ran `gittio demo dk.napp.drawer` to create a project with just the module and its sample and run that on iOS Simulator and saw the same.

So closing it as a module issue. Please report it at
https://github.com/viezel/NappDrawer
