### ISSUE TITLE
Use this in combination with https://github.com/FokkeZB/Template.Hierarchical-Navigation

### ISSUE THREAD

**Issue by SudoPlz** [FokkeZB/nl.fokkezb.drawer#59]
Hello Fokke,

I’m really trying hard to create a base for my app that includes:

* A drawer
* Hierarchical navigation that also uses a bar.

for BOTH iOS and Android..!

In essence I want to combine both [FokkeZb/Template.Hierarchical-Navigation](https://github.com/FokkeZB/Template.Hierarchical-Navigation) AND [FokkeZb/nl.fokkezb.drawer](https://github.com/FokkeZB/nl.fokkezb.drawer) in my app.. How can I do this without problems?

Thank you!

**Comment by FokkeZB** [comment]
The sample in the [README](https://github.com/FokkeZB/nl.fokkezb.drawer) does that for both iOS and Android (see the notes on using *DrawerLayout*).

**Comment by SudoPlz** [comment]
I don't see where Hierarchical Navigation takes place. Would you please help me find that?

**Comment by SudoPlz** [comment]
Nevermind, since I wasn't able to do this I used [this project](https://github.com/yomybaby/kr.yostudio.drawer).

 I leave this here in case someone else wishes to do the same.

**Comment by FokkeZB** [comment]
Wow, nice one!
