### ISSUE TITLE
lifecycleContainer (Android)

### ISSUE THREAD

**Issue by nitrag** [FokkeZB/nl.fokkezb.drawer#60]
I'm using a component that needs to know the lifecycleContainer. What would be the lifecycleContainer in this case for android? 

$.drawer?
the left window?

**Comment by FokkeZB** [comment]
That question isn't related to the widget but the module (https://github.com/viezel/NappDrawer or https://github.com/manumaticx/Ti.DrawerLayout) you use. See https://github.com/viezel/NappDrawer/blob/master/android/example/app.js for how you get the activity for Napp Drawer. You can get the drawer instance from the widget via the exported `instance` property.
