### ISSUE TITLE
Events not firing (windowDidOpen, windowDidClose) on android

### ISSUE THREAD

**Issue by daniila** [FokkeZB/nl.fokkezb.drawer#61]
Hi!

It seems to be an issue with this widget, as I tested NappDrawer's example code in a classical titanium app and it worked like it should.

Here's how I've got it setup:

index.xml
```
<Alloy>
	<Widget id="wupApp" src="nl.fokkezb.drawer">		
        <Window module="xp.ui" role="leftWindow">
        	<Require type="view" src="nav" id="nav" />
        </Window>
		
        <View platform="android" role="centerWindow">
            <Require type="view" src="mainview" id="mainview" />
        </View>
		
        <Window module="xp.ui" role="rightWindow">
            <Label>I am right</Label>
        </Window>
	</Widget>
</Alloy>
```

index.js
```
$.wupApp.addEventListener('windowDidOpen',function(e){
	alert('Window opened');
});

$.wupApp.addEventListener('windowDidClose',function(e){
	alert('Window Closed');
});

$.wupApp.open();
```
index.tss
```
"#wupApp": {
    openDrawerGestureMode: "OPEN_MODE_ALL",
    closeDrawerGestureMode: "CLOSE_MODE_MARGIN",
    leftDrawerWidth: Alloy.Globals.drawerWidth,
	
    // use DrawerLayout for Android
    drawerLayout: true
}
```

And none of the events get fired, not with sliding or tapping the home icon.

**Comment by daniila** [comment]
I feel really stupid now. As soon as I posted this I realized maybe the DrawerLayout module and NappDrawer have their own events. And sure enough that was the case. So just in case anyone else has the same issue:

```
$.drawer.addEventListener('draweropen',function(){});
$.drawer.addEventListener('drawerclose',function(){});
```

are the events you need to use if you're using the drawerLayout module.

**Comment by FokkeZB** [comment]
Still.. it would be nice if the widget would take care of that difference.

**Comment by FokkeZB** [comment]
Could you test the master version? I've just made a change:
https://github.com/FokkeZB/nl.fokkezb.drawer/commit/c580bfc7a44fcb8b1d070ceacea3e747d2c0e72d

Via gittio: `gittio install nl.fokkezb.drawer@master`

**Comment by daniila** [comment]
Tested it, the events get fired correctly. One issue with this is though, the modules have slightly different event signatures, so you'd still have to account for which one you're using.
Which drawer opened with drawerLayout:
```
if(e.drawer === 'left'){}
```
Nappdrawer
```
if(e.window === NappDrawerModule.LEFT_WINDOW) {} 
```
NappDraweModule.LEFT_WINDOW is an integer.

**Comment by FokkeZB** [comment]
Mmm, I'm afraid I can't go as far as translating all payload differences. So you'll have to handle that in your callback.
