### ISSUE TITLE
Android crashed when using role="rightWindow"

### ISSUE THREAD

**Issue by abada** [FokkeZB/nl.fokkezb.drawer#62]
In my project i want using centerWindow and rightWindow , and set  drawerLayout: false for using NappDrawer , it works fine on ios , but in android app crashed ! 

if i used role="leftWindow" it working fine ! , but i want use role="rightWindow"

**Comment by FokkeZB** [comment]
I think NappDrawer requires a rightWindow with optional leftWindow, but I'm not sure. Try doing both?

**Comment by abada** [comment]
It works after added just `<Window module="xp.ui"   role="leftWindow"></Window>`
 
thank you :)
