### ISSUE TITLE
setRightView programmatically?

### ISSUE THREAD

**Issue by nitrag** [FokkeZB/nl.fokkezb.drawer#63]
I have tried this with and without an initial right window, doesn't work. I don't get any errors.

I want to have some pages have a right window and others not. Possible? 

~~~
var filterView = Ti.UI.createView({height: Ti.UI.FILL, width: Ti.UI.FILL, backgroundColor: '#000', opacity: 0.5});
Alloy.Globals.Drawer.setRightView(filterView);
function toggleFilter(){
	Alloy.Globals.Drawer.toggleRightWindow();
	Ti.API.info("Filter clicked");	
}
~~~

**Comment by nitrag** [comment]
Well matter of fact it is working in Android. Must be nappdrawer bug for iOS.

Sorry to bother again Fokke.

**Comment by FokkeZB** [comment]
On iOS the drawers must be windows, not views. So I guess that's the problem.

**Comment by nitrag** [comment]
Hmm, still not working...

I setup an initial right window on app load. It works fine until I use setRightWindow (also tried setRightView). Seems to break there.

Page with filter button. Prior to hitting filter button i can swipe to open the drawer that has the default RightWindow. As soon as I try to replace the RightWindow, it breaks.
~~~
var filterView;
function toggleFilter(){
	if(!filterView){
		filterView = Alloy.createController('utilities/trailFilter', {
			id: 'test123'
		}).getView();
		Alloy.Globals.Drawer.setRightWindow(filterView);
	}
	Alloy.Globals.Drawer.toggleRightWindow();
	Ti.API.info("Filter clicked");	
}
~~~

trailFilter.xml
~~~
<Alloy>
    <Window module="xp.ui" id="win" role="rightWindow" backgroundColor="#000">
        <Label color="#FFFFFF">I am Filter</Label>
    </Window>
</Alloy>
~~~

**Comment by FokkeZB** [comment]
This might be a widget issue after all.

As you can see I map `setRightWindow(val)` to `rightWindow = val`:
https://github.com/FokkeZB/nl.fokkezb.drawer/blob/master/nl.fokkezb.drawer/controllers/widget.js#L178-L185

Could you try to see if `Alloy.Globals.Drawer.instance.setRightWindow(val)` works? That calls directly on the module.

**Comment by nitrag** [comment]
Ok it's not the widget. Or needing to add "instance". Both will fire the
modules "setRightWindow". I figured this out by forking NappDrawer and
added some debug code. It's locking up.

Thanks for the help!

~~~
...
[DEBUG] Clearing Right Window
[INFO]  Filter clicked
(((locked up here)))
~~~
https://github.com/nitrag/NappDrawer/blob/master/ios/Classes/DkNappDrawerDrawer.m#L264-L268

**Comment by nitrag** [comment]
Wait.....maybe it has something to do with these "args". I'm a n00b with
modules, these things are coming slow to me.

**Comment by nitrag** [comment]
Ok, I apologize for my back and forth. I'm a noob at this so I keep confusing myself.

It appears that using either:
~~~
Alloy.Globals.Drawer.setRightWindow(filterView);
Alloy.Globals.Drawer.instance.setRightWindow(filterView);
~~~

This will fire dk.napp.drawer's setRightWindow BUT for some reason the module receives the "args" is blank or something which is why we see the "Clearing Right Window" debug message...?

This is so strange because I use:
~~~
$.drawer.setCenterWindow(newPage.getView());
~~~
In a different part of my app and it works fine. The module's code is the same!

**Comment by FokkeZB** [comment]
Ah, so it looks like a module bug then? Could you report that at the NappDrawer repo?
