### ISSUE TITLE
Back button events not working for android

### ISSUE THREAD

**Issue by Niral2110** [FokkeZB/nl.fokkezb.drawer#64]
Due to compulsory use of `<View>` instead of `<Window>` for android devices, I am not able to get any `<Window>` related event (i.e. resume, pause) as well as when I hit hard Back button on device, app gets crashed.
Please suggest a solution to work out for back button & resume/pause, focus/blur events for android device.
I am stuck in an urgent issue, immidiate help would be really appericiated.
Thanks in advance.

**Comment by FokkeZB** [comment]
This is not related to the widget. Depending on what module you use, please see the documentation of http://gitt.io/component/dk.napp.drawer or https://github.com/manumaticx/Ti.DrawerLayout on how to access the drawer's activity for these events.
