### ISSUE TITLE
Error with module = 'xp.ui'

### ISSUE THREAD

**Issue by annamf** [FokkeZB/nl.fokkezb.drawer#66]
I'm trying to install this widget but this module gives me an error, and I can't found this module anywhere.

```
<Window module="xp.ui" role="leftWindow">
            <Label>I am left</Label>
</Window>
```

The error:
`Script Error Couldn't find module: xp.ui for architecture: armv7`

**Comment by adamkearsley** [comment]
create a file in your app/lib folder with the following

```
exports.createWindow = function(args) {
    return Ti.UI[OS_IOS ? 'createWindow' : 'createView'](args);
    return;
};
```

**Comment by annamf** [comment]
What name of this file?

**Comment by adamkearsley** [comment]
app/lib/xp.ui.js updated the reply above.
