### ISSUE TITLE
Android - Put widget in centerWindow

### ISSUE THREAD

**Issue by annamf** [FokkeZB/nl.fokkezb.drawer#69]
Hello, I'm trying to put a Widget into the center window on **Android** but the **tss** rules doesn't work (backgroundColor, height, width,.... ) of any UI element of the widget. On iOS works perfectly.

In the left window the Label not shown too.

This is my index.xml
```
<Alloy>
	<Widget id="drawer" src="nl.fokkezb.drawer">

        <Window module="xp.ui" role="leftWindow">
            <Label>I am left</Label>
        </Window>

        <View platform="android" id="centerWindow" role="centerWindow">
       		<Widget src="es.toolbar" id="toolbar"/>
       </View>

    </Widget>
</Alloy>
```
index.tss

```
"#drawer": {
    openDrawerGestureMode: "OPEN_MODE_ALL",
    closeDrawerGestureMode: "CLOSE_MODE_ALL",
    leftDrawerWidth: 200,
    showShadow: false
}

"#drawer[platform=android]":{
    // use DrawerLayout for Android
    drawerLayout: true
}

"Window": {
    backgroundColor: 'white'
}

"#centerWindow":{
	layout: 'vertical'
}

"#centerWindow[platform=android]":{
	
}

"#win[platform=ios]":{
	barColor: '#38505e',
	layout: 'vertical',
	translucent: false
}
```

And my widget.xml

```
<Alloy>
	<View id="board">
	    <ScrollView id="toolbar"></ScrollView>
	    <ScrollableView id="lists" showPagingControl="false"></ScrollableView>
    </View>
</Alloy>
```
widget.tss

```
"#board":{
	layout: 'vertical'
}

"#toolbar": {
	backgroundColor: '#46acd8',
	height: 50,
	width: Ti.UI.SIZE,
	layout: 'horizontal',
	top: 0,
	scrollType: 'horizontal'
}
```
Thank you.

**Comment by FokkeZB** [comment]
You didn't include the actual TSS.

Did you have a look at the compiled code (in `/Resources`) to debug this?

**Comment by annamf** [comment]
Added the tss. I debug it, but I can't find what is wrong....

**Comment by FokkeZB** [comment]
In the compiled widget (look it up under `/Resources`) do you see these properties appear? What Alloy version are you using?

Btw, this doesn't seem related to this drawer widget but rather an Alloy bug - if any.

**Comment by annamf** [comment]
Yes, it's because width: Ti.UI.SIZE on scrollView. Just right now I found it. 
with '100%' it works...
