### ISSUE TITLE
get activity of the main window

### ISSUE THREAD

**Issue by LudoFont** [FokkeZB/nl.fokkezb.drawer#70]
Hi,
I don't understand why I can't get the activity of the android version of my app. In fact, there is no trigger of the event 'open' in my index.

Code :

**index.xml :**
```
<Alloy>
	<Widget id="index" src="nl.fokkezb.drawer">
	 	<Window id="left" module="xp.ui" role="leftWindow">
            <Require src="menu"></Require>
        </Window>
		<Window id="center" module="xp.ui" role="centerWindow">
            
		</Window>
	</Widget>
</Alloy>
```

**index.js :**
```
function toggle(e) {
    var fn = 'toggle' + e.source.title + 'Window';
    $.index[fn]();
}

$.index.on('open', function (e) {
	console.log("IT'S TRIGGER !");
	var actionBar = e.source.getActivity().getActionBar();
	actionBar.title = "My app";
});

$.index.open();
```

I tried **$.index**, **$.window**, **$.index.instance**, **$.index.module**, with **on** or **addEventListener** ... no trigger of open :(

**Comment by LudoFont** [comment]
I found a way but I think it's not the best practice :
`$.index.instance.getParent().on('open', function (e) { ...`

**Comment by FokkeZB** [comment]
I think you're using the widget with DrawerLayout? In that case you need `$.index.window`, just like I do here: https://github.com/FokkeZB/nl.fokkezb.drawer/blob/master/nl.fokkezb.drawer/controllers/widget.js#L112

**Comment by LudoFont** [comment]
yep that's right, perfect !

thank you for your answer & your awesome module !
