### ISSUE TITLE
programmatically call arrow animation

### ISSUE THREAD

**Issue by LudoFont** [FokkeZB/nl.fokkezb.drawer#72]
Hi,

For navigation purpose, in my app (on android with the DrawerLayout module) I change the burger icon by the arrow icon when I go in secondary page with the method : 
`$.index.setDrawerIndicatorEnabled(true);`
This works but I don't have the animation of the icon change (like this one when you open the drawer).
Is there a way to programmatically call the animation ?

Thank's,

Ludovic F.

**Comment by FokkeZB** [comment]
Hi,

That's more a question for the module. Could you file it there?
https://github.com/manumaticx/Ti.DrawerLayout/issues
