### ISSUE TITLE
error deploying for ios 10 - couldn't find module com.tripvi.drawerlayout

### ISSUE THREAD

**Issue by inaffect-ag** [FokkeZB/nl.fokkezb.drawer#76]
when i deploy for ios, i get the error: **couldn't find module com.tripvi.drawerlayout** - but drawerlayout is only an android module, and also in tiapp.xml it is installed only for android. the iphone should use the installed napp drawer...
`<module platform="android">com.tripvi.drawerlayout</module>` and `<module platform="iphone">dk.napp.drawer</module>`

any idea what could be the error?

i'm using:
com.tripvi.drawerlayout v.2.0.0
dk.napp.drawer v.1.2.4
nl.fokkezb.drawer v.1.1.2

**Comment by FokkeZB** [comment]
Could you check all of the compiled Alloy code in the `Resources` folder for references of `com.tripvi.drawerlayout`?

The widget should only require the module on Android:
https://github.com/FokkeZB/nl.fokkezb.drawer/blob/master/nl.fokkezb.drawer/controllers/widget.js#L5-L9

**Comment by inaffect-ag** [comment]
you were right - i had a forgotten `require('com.tripvi.drawerlayout')` in one of my views...
thanks a lot!!

**Comment by FokkeZB** [comment]
No problem!
