### ISSUE TITLE
gitt.io still shows and install by default version 1.1.2 should be 1.1.3

### ISSUE THREAD

**Issue by alangumer** [FokkeZB/nl.fokkezb.drawer#79]

**Comment by FokkeZB** [comment]
I've removed the package from NPM and bumped the `widget.json` which was indeed still 1.1.2.

Thanks!

**Comment by alangumer** [comment]
thank you! I guess is gonna take some time to see the new version in http://gitt.io/component/nl.fokkezb.drawer
