### ISSUE TITLE
Invalid Tab child "Alloy.Widget"

### ISSUE THREAD

**Issue by dbenhenni** [FokkeZB/nl.fokkezb.drawer#80]
Hi,
glad to see the drawer for alloy. Unfortunately I need the widget inside of a tabgroup getting the following error:

[ERROR] :  Invalid Tab child "Alloy.Widget"
[ERROR] :  Tab must have only one child element, which must be a Window
[ERROR] :  Alloy compiler failed

**Comment by FokkeZB** [comment]
@dbenhenni that's a limitation of Titanium I can't do anything about, sorry.
